# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSCase
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'
  
  target 'IOSCaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSCaseUITests' do
    # Pods for testing
  end

end
